
  
env:
  global:
    - email=`git log -1 --pretty=format:'%ae'`
    
language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage==4.3
  - pip install pandas
  - pip install xlrd
  - pip install codeclimate-test-reporter


script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pwd
  - cd Function
  - python Run_Pipline.py
  - bash Running_Function.sh
  - python CoverageCombine.py
  - bash Coverage_Function.sh
  - cd ..

after_failure:
  - echo "Because this is a Organization GIT"


git:
  depth: 2
  
branches:
  only:
   - gh-pages
after_success:
#    - coveralls
#    - codecov
    


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages
    condition: $email != deploy@travis-ci.org
    


after_deploy:
  - git push origin master

after_failure:
  - echo problem


    
notifications:
  email:
    recipients:
   #   - prithvisekhp@xxx.com #default sends to registered email
    on_success: always
    on_failure: always
